### ISSUE TITLE
Add missing graphql dependencies

### ISSUE THREAD

**Issue by gastaldi** [smallrye/smallrye-bom#102]
These dependencies are missing in the BOM. /cc @phillip-kruger 

- `io.smallrye:smallrye-graphql-cdi`
- `io.smallrye:smallrye-graphql-schema-builder`
- `io.smallrye:smallrye-graphql-ui-graphiql`

**Comment by gastaldi** [comment]
Also `smallrye-graphql-cdi`

**Comment by phillip-kruger** [comment]
Thanks, I'll add it. Also need to update open api version to 2.x

**Comment by gastaldi** [comment]
I think @dependabot should pick that version bump anyway, but that's cool :+1:

**Comment by phillip-kruger** [comment]
How can we tell dependabot to go to 2.x ? Seems like it's stuck on 1.x

**Comment by gastaldi** [comment]
Weird, I wonder if there is something configured in app.dependabot.com to not bump major versions?

**Comment by phillip-kruger** [comment]
I'll also do health (ui) and mutiny in one PR.
