### ISSUE TITLE
Add Mutiny and reactive dependencies

### ISSUE THREAD

**Issue by gastaldi** [smallrye/smallrye-bom#103]
/cc @cescoffier

**Comment by phillip-kruger** [comment]
I am on it.

**Comment by gastaldi** [comment]
@phillip-kruger hero :smiley:

**Comment by cescoffier** [comment]
I missed the context, what's this BOM? 
I would prefer not having to update another project after the reactive components releases.

**Comment by gastaldi** [comment]
This BOM is updated by dependabot so you don't need to do anything else after releasing your stuff 😉

**Comment by cescoffier** [comment]
Great! Who is going to consume this BOM? 

@phillip-kruger Don't forget reactive-utils. It's the glue.

**Comment by gastaldi** [comment]
@cescoffier Quarkus of course, and any other project that requires SmallRye :)
